### PR TITLE
fix GPU bug from sif model

### PR DESCRIPTION
**Pull request by AlexisRenchon**
Fix GPU bug from sif model

Closes #719

Closes #717

### CODE REVIEW

**Comment by AlexisRenchon** [comment]
not sure why buildkite is failing now 
```
ERROR: LoadError: Cannot locate artifact 'era5_land_forcing_data2021' for x86_64-linux-gnu-libgfortran5-cxx11-libstdcxx30-julia_version+1.10.3 in '/central/scratch/esm/slurm-buildkite/climaland-ci/4745/climaland-ci/Artifacts.toml'
```
it passed just before, I just squashed.

**Comment by AlexisRenchon** [comment]
worked on GPU:
```
[arenchon@hpc-22-32 ClimaLand.jl]$ julia -i --project=.buildkite experiments/benchmarks/land.jl
[ Info: Run: Global RichardsModel
[ Info: Resolution: (101, 15)
[ Info: Timestep: 900.0 s
[ Info: Duration: 21600.0 s
[ Info: Starting profiling
[ Info: Num samples: 28
[ Info: Average time: 14.7 s
[ Info: Max time: 14.8 s
[ Info: Min time: 14.6 s
[ Info: Standard deviation time: 0.00361 s
[ Info: Done profiling
[ Info: Saved compute flame to land_benchmark_gpu/flame_gpu.html
[ Info: Saved allocation flame to land_benchmark_gpu/alloc_flame_gpu.html
```

**Comment by AlexisRenchon** [comment]
note this PR contains the change in #717 so we can close it after this is merged

**Review by Sbozzolo — APPROVED** [review]

**Comment by AlexisRenchon** [comment]
@kmdeck 

Hello Kat! 
Can you look at this PR? More specifically, the error related to the albedo Artifact... 

This PR was passing CI at some point, then there was a problem with not finding the albedo file in Caltech box so we changed it, but now one of the test fail

**Comment by kmdeck** [comment]
> @kmdeck
> 
> Hello Kat! Can you look at this PR? More specifically, the error related to the albedo Artifact...
> 
> This PR was passing CI at some point, then there was a problem with not finding the albedo file in Caltech box so we changed it, but now one of the test fail

I am taking a look now. I dont understand what happened with the file, but there are still NaNs present. maybe that is why it isnt passing? https://github.com/CliMA/ClimaLand.jl/actions/runs/10378241417/job/28734087789?pr=719#step:6:581

**Comment by AlexisRenchon** [comment]
> > @kmdeck
> > Hello Kat! Can you look at this PR? More specifically, the error related to the albedo Artifact...
> > This PR was passing CI at some point, then there was a problem with not finding the albedo file in Caltech box so we changed it, but now one of the test fail
> 
> I am taking a look now. I dont understand what happened with the file, but there are still NaNs present. maybe that is why it isnt passing? https://github.com/CliMA/ClimaLand.jl/actions/runs/10378241417/job/28734087789?pr=719#step:6:581

does this look ok? 
https://github.com/CliMA/ClimaLand.jl/pull/719/commits/c546593a5abc73bb5706bf835c6a4c12f76b4f32

I think there's two albedo files, and we weren't sure which one to pick

sw_albedo_Amon_CESM2_historical_r1i1p1f1_gn_185001-201412_v2_no-nans.nc
And
sw_albedo_Amon_CESM2_historical_r1i1p1f1_gn_185001-201412_v2.nc

I am surprised the "no_nans" actually has nans.

**Pull request merged**
