### PR TITLE
tag 0.12.3

### PR DESCRIPTION
**Pull request by AlexisRenchon**
## Purpose 

tag bi-weekly release

### CODE REVIEW

**Comment by AlexisRenchon** [comment]
@kmdeck CI error from the snow model - is that an easy fix? (I'll have a look too)

```
  1 dependency had output during precompilation:
┌ KrylovKit
│  WARNING: using ChainRulesCore.add!! in module KrylovKit conflicts with an existing identifier.
└  
     Testing Running tests...
Test Summary: | Pass  Total   Time
Aqua tests    |   10     10  11.5s
Test Summary:                              | Pass  Total   Time
Richards model implicit timestepping tests |   52     52  52.8s
Test Summary:        | Pass  Total   Time
Domains module tests |   59     59  14.5s
Test Summary:           | Pass  Total   Time
General utilities tests |   43     43  13.8s
Test Summary:        | Pass  Total  Time
Variable types tests |   42     42  0.6s
Test Summary: | Pass  Total  Time
Driver tests  |   51     51  2.2s
Test Summary:             | Pass  Total   Time
Bucket albedo types tests |   17     17  26.9s
Test Summary:     | Pass  Total     Time
Bucket snow tests |   76     76  1m07.1s
Test Summary:     | Pass  Total  Time
Bucket soil tests |   52     52  7.5s
Snow Parameterizations, FT = Float32: Test Failed at /Users/runner/work/ClimaLand.jl/ClimaLand.jl/test/standalone/Snow/parameterizations.jl:81
  Expression: all(q_l[T_bulk .< _T_freeze] .< eps(FT))
  ```

**Comment by kmdeck** [comment]
> @kmdeck CI error from the snow model - is that an easy fix? (I'll have a look too)
> 
> ```
>   1 dependency had output during precompilation:
> ┌ KrylovKit
> │  WARNING: using ChainRulesCore.add!! in module KrylovKit conflicts with an existing identifier.
> └  
>      Testing Running tests...
> Test Summary: | Pass  Total   Time
> Aqua tests    |   10     10  11.5s
> Test Summary:                              | Pass  Total   Time
> Richards model implicit timestepping tests |   52     52  52.8s
> Test Summary:        | Pass  Total   Time
> Domains module tests |   59     59  14.5s
> Test Summary:           | Pass  Total   Time
> General utilities tests |   43     43  13.8s
> Test Summary:        | Pass  Total  Time
> Variable types tests |   42     42  0.6s
> Test Summary: | Pass  Total  Time
> Driver tests  |   51     51  2.2s
> Test Summary:             | Pass  Total   Time
> Bucket albedo types tests |   17     17  26.9s
> Test Summary:     | Pass  Total     Time
> Bucket snow tests |   76     76  1m07.1s
> Test Summary:     | Pass  Total  Time
> Bucket soil tests |   52     52  7.5s
> Snow Parameterizations, FT = Float32: Test Failed at /Users/runner/work/ClimaLand.jl/ClimaLand.jl/test/standalone/Snow/parameterizations.jl:81
>   Expression: all(q_l[T_bulk .< _T_freeze] .< eps(FT))
> ```

I have seen this too. It seems intermittent, though.... I just retried the job in CI, let's see if it passes. we should fix this at some point...

**Comment by AlexisRenchon** [comment]
@kmdeck there is also an error to build the snow tutorial in the docs (see CI) - did you see that before?

**Comment by kmdeck** [comment]
> @kmdeck there is also an error to build the snow tutorial in the docs (see CI) - did you see that before?

I have not seen it, but perhaps @a-charbon has? https://github.com/CliMA/ClimaLand.jl/actions/runs/9473604094/job/26101550233?pr=653#step:5:48

**Comment by kmdeck** [comment]
By the way, I was trying to run a coupled run with the latest climaland, and there is a bug.

@Sbozzolo added the thermo_params to the PrescribedAtmosphere object: https://github.com/CliMA/ClimaLand.jl/blob/97f06a17e349b8666b6b73d89657b4bdaae03c4a/src/shared_utilities/drivers.jl#L89

and since we effectively specify this multiple times in the model, there is also this check:
https://github.com/CliMA/ClimaLand.jl/blob/97f06a17e349b8666b6b73d89657b4bdaae03c4a/src/shared_utilities/models.jl#L391

which will fail when we use the CoupledAtmosphere atmos type.

I am trying to fix this ahead of time before we do this release

**Review by kmdeck — APPROVED** [review]
all set now, I think!

**Comment by kmdeck** [comment]
> > > @kmdeck there is also an error to build the snow tutorial in the docs (see CI) - did you see that before?
> > 
> > 
> > I have not seen it, but perhaps @a-charbon has? https://github.com/CliMA/ClimaLand.jl/actions/runs/9473604094/job/26101550233?pr=653#step:5:48
> 
> @kmdeck @AlexisRenchon The lack of a "Date" column comes when the data scraping portal called in the code block via the `sitedata_daily()` or `sitedata_hourly()` functions doesn't return a webpage at all or returns a data error page, such as trying to scrape too large of a file (which shouldn't happen since the size of the csv I scrape in the tutorial doesn't change over time) or the website is down. This is usually transient and an issue on the data-website side from it being down temporarily, and goes away by running again (just trying to scrape the information again).
> 
> I would assume this is the case since this code hasn't been touched in months and works on other builds? I just checked the data portal site and requested a CSV, and received what should come through.

Thanks for the update, Andy!

**Pull request merged**
